name: CD for GitHub Pages

on:
  push:
    branches: '**'

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Build usage page
      uses: actions/jekyll-build-pages@v1
      with:
        source: usage
        destination: src/usage
    - name: Fix path in usage/index.html to relative
      run: |
        cd src/usage
        mv index.html index-bac.html
        sed -e 's/"\/SeatLottery/./g' index-bac.html > index.html
        rm index-bac.html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: src


  # GitHub Pages deployment
  deploy-pages:
    # Deployment for only main branch, build steps are for all
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    needs: build-site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
    - name: Deploy pages
      id: deploy-pages
      uses: actions/deploy-pages@v4
